import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/partials/Header";
import Footer from "@/components/partials/Footer";
import { StoreProvider } from "@/provider/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Reeco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative overflow-x-hidden`}>
        <StoreProvider>
          <Header />
          <div className="w-full absolute">
            <main className="min-h-[868px] bg-gray-200">{children}</main>
            <div className="w-full absolute bottom-auto">
              <Footer />
            </div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
